import { useEffect, useState } from 'react';
import PageHeader from '../../components/ui/PageHeader.jsx';
import Card from '../../components/ui/Card.jsx';
import Badge from '../../components/ui/Badge.jsx';
import Button from '../../components/ui/Button.jsx';
import Modal from '../../components/ui/Modal.jsx';
import { Textarea } from '../../components/ui/Input.jsx';
import Loader from '../../components/ui/Loader.jsx';
import ErrorBanner from '../../components/ui/ErrorBanner.jsx';
import { aiApi } from '../../api/aiApi.js';
import { formatDate } from '../../utils/formatDate.js';

export default function AIContent() {
  const [items, setItems] = useState([]);
  const [editing, setEditing] = useState(null);
  const [content, setContent] = useState('');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  const load = async () => { setLoading(true); try { setItems(await aiApi.getAIContent()); } catch (err) { setError(err?.response?.data?.message || err.message || 'Could not load AI content'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const save = async () => { setSaving(true); try { await aiApi.updateAIContent(editing._id, content); setEditing(null); await load(); } catch (err) { setError(err?.response?.data?.message || err.message || 'Could not update content'); } finally { setSaving(false); } };

  return (
    <div>
      <PageHeader eyebrow="AI Studio" title="Saved AI content" description="Review and edit proposals, follow-ups, and insight content generated by AI." />
      <ErrorBanner message={error} />
      {loading ? <Loader label="Loading AI content" /> : <div className="grid gap-4 xl:grid-cols-2">{items.map((item) => <Card key={item._id}><div className="mb-3 flex items-center justify-between"><Badge status={item.type}>{item.type}</Badge><span className="text-xs font-bold text-muted">{formatDate(item.createdAt)}</span></div><p className="line-clamp-6 whitespace-pre-wrap text-sm leading-7 text-muted">{item.editedContent || item.content}</p><Button className="mt-4" variant="secondary" size="sm" onClick={() => { setEditing(item); setContent(item.editedContent || item.content || ''); }}>Edit</Button></Card>)}{!items.length ? <Card><p className="text-sm text-muted">No AI content generated yet.</p></Card> : null}</div>}
      <Modal open={Boolean(editing)} title="Edit AI content" onClose={() => setEditing(null)} footer={<div className="flex justify-end gap-3"><Button variant="secondary" onClick={() => setEditing(null)}>Cancel</Button><Button loading={saving} onClick={save}>Save changes</Button></div>}>
        <Textarea className="min-h-96" value={content} onChange={(e) => setContent(e.target.value)} />
      </Modal>
    </div>
  );
}
